/* ============================================================
   Inline-stilobjektet (S) från prototypen, samlat på ett ställe.
   Utseendet är oförändrat. BURGUNDY hämtas från tokens.
   ============================================================ */

import type { CSSProperties } from "react";
import { BURGUNDY } from "./tokens";

export const S: Record<string, CSSProperties> = {
  app: {
    fontFamily: "'Inter', system-ui, sans-serif",
    maxWidth: 1100,
    margin: "0 auto",
    padding: 20,
    color: "#1a1a1a",
    background: "#faf8f6",
    minHeight: "100vh",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    flexWrap: "wrap",
    gap: 16,
  },
  title: { fontSize: 30, fontWeight: 800, letterSpacing: -1, margin: 0 },
  subtitle: {
    color: "#888",
    fontSize: 13,
    letterSpacing: 2,
    textTransform: "uppercase",
    marginTop: 2,
  },
  dateBox: { textAlign: "right" },
  dateLabel: { fontSize: 11, color: "#999", letterSpacing: 2 },
  dateValue: { fontSize: 22, fontWeight: 700 },
  nextBtn: {
    marginTop: 6,
    background: BURGUNDY,
    color: "#fff",
    border: "none",
    padding: "10px 18px",
    borderRadius: 8,
    fontWeight: 600,
    fontSize: 14,
  },
  miniBtn: {
    background: "#fff",
    border: "1px solid #ddd",
    padding: "5px 10px",
    borderRadius: 6,
    fontSize: 12,
    fontWeight: 600,
  },
  statRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit,minmax(150px,1fr))",
    gap: 10,
    marginTop: 18,
  },
  stat: { background: "#fff", border: "1px solid #eee", borderRadius: 10, padding: "12px 14px" },
  statLabel: { fontSize: 11, color: "#999", letterSpacing: 1, textTransform: "uppercase" },
  statValue: { fontSize: 19, fontWeight: 700, marginTop: 2 },
  statSub: { fontSize: 11, color: "#999", marginTop: 1 },
  tabs: {
    display: "flex",
    gap: 4,
    marginTop: 22,
    borderBottom: "2px solid #eee",
    flexWrap: "wrap",
  },
  tab: {
    background: "none",
    border: "none",
    padding: "10px 16px",
    fontSize: 14,
    fontWeight: 600,
    color: "#999",
    borderBottom: "2px solid transparent",
    marginBottom: -2,
  },
  tabActive: { color: BURGUNDY, borderBottom: `2px solid ${BURGUNDY}` },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill,minmax(260px,1fr))",
    gap: 14,
    marginTop: 18,
  },
  card: {
    background: "#fff",
    border: "1px solid #eee",
    borderRadius: 12,
    padding: 16,
    boxShadow: "0 1px 3px rgba(0,0,0,.04)",
  },
  cardHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  badge: {
    background: BURGUNDY,
    color: "#fff",
    fontSize: 11,
    fontWeight: 600,
    padding: "3px 8px",
    borderRadius: 6,
  },
  cardDistrict: { fontSize: 13, color: "#888", fontWeight: 600 },
  cardValue: { fontSize: 22, fontWeight: 800, marginBottom: 10 },
  cardRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 13,
    padding: "3px 0",
    color: "#444",
  },
  condBar: {
    position: "relative",
    width: 90,
    height: 16,
    background: "#eee",
    borderRadius: 8,
    overflow: "hidden",
    display: "inline-block",
  },
  condFill: { position: "absolute", left: 0, top: 0, bottom: 0, borderRadius: 8 },
  condText: {
    position: "absolute",
    right: 6,
    top: 0,
    fontSize: 11,
    fontStyle: "normal",
    fontWeight: 700,
    color: "#fff",
    lineHeight: "16px",
  },
  tenantBox: { background: "#f7f2f4", borderRadius: 8, padding: "8px 10px", margin: "8px 0" },
  vacantBox: {
    background: "#fff6f0",
    borderRadius: 8,
    padding: "8px 10px",
    margin: "8px 0",
    fontSize: 12,
    color: "#a05000",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  leaseBtn: {
    background: BURGUNDY,
    color: "#fff",
    border: "none",
    padding: "6px",
    borderRadius: 6,
    fontWeight: 600,
    fontSize: 12,
  },
  upgRow: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 6, marginTop: 12 },
  upgBtn: {
    background: "#f3eef0",
    border: `1px solid ${BURGUNDY}33`,
    color: BURGUNDY,
    fontSize: 12,
    fontWeight: 600,
    padding: "7px 4px",
    borderRadius: 6,
  },
  upgDone: { background: "#eef5ee", color: "#27660a", border: "1px solid #27660a33" },
  sellBtn: {
    width: "100%",
    marginTop: 12,
    background: "#fff",
    border: "1px solid #ddd",
    color: "#7a5a00",
    padding: "9px",
    borderRadius: 8,
    fontWeight: 600,
    fontSize: 13,
  },
  buyBtn: {
    width: "100%",
    marginTop: 12,
    background: BURGUNDY,
    color: "#fff",
    border: "none",
    padding: "10px",
    borderRadius: 8,
    fontWeight: 700,
    fontSize: 14,
  },
  btnDisabled: { background: "#ccc", color: "#fff" },
  select: {
    width: "100%",
    marginTop: 8,
    padding: "8px",
    borderRadius: 8,
    border: "1px solid #ddd",
    fontSize: 13,
  },
  marketBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 18,
    fontWeight: 700,
    fontSize: 15,
  },
  smallBtn: {
    background: "#fff",
    border: "1px solid #ddd",
    padding: "7px 12px",
    borderRadius: 8,
    fontWeight: 600,
    fontSize: 13,
  },
  empty: {
    gridColumn: "1/-1",
    textAlign: "center",
    color: "#999",
    padding: 40,
    background: "#fff",
    borderRadius: 12,
    border: "1px dashed #ddd",
  },
  logBox: {
    marginTop: 18,
    background: "#fff",
    border: "1px solid #eee",
    borderRadius: 12,
    padding: 16,
    maxHeight: 440,
    overflowY: "auto",
  },
  logItem: { fontSize: 13, padding: "5px 0", borderBottom: "1px solid #f3f3f3" },
  financeWrap: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 18, marginTop: 18 },
  financeCol: { background: "#fff", border: "1px solid #eee", borderRadius: 12, padding: 18 },
  h3: { fontSize: 15, fontWeight: 700, margin: "0 0 10px", color: BURGUNDY },
  amortRow: { display: "flex", alignItems: "center", gap: 10, marginTop: 8 },
  amortBtn: {
    width: "100%",
    marginTop: 10,
    background: BURGUNDY,
    color: "#fff",
    border: "none",
    padding: "10px",
    borderRadius: 8,
    fontWeight: 700,
  },
  gameOver: {
    marginTop: 16,
    background: "#fff0f0",
    border: "1px solid #f0c0c0",
    color: "#c0392b",
    padding: 16,
    borderRadius: 12,
    fontWeight: 600,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
  },
  resetBtn: {
    background: BURGUNDY,
    color: "#fff",
    border: "none",
    padding: "8px 16px",
    borderRadius: 8,
    fontWeight: 600,
  },
  footer: { marginTop: 30, color: "#aaa", fontSize: 12, textAlign: "center" },

  // ── New split-layout styles ────────────────────────────────────
  toolbar: { display:"flex", alignItems:"center", height:46, background:"#1e0e12", padding:"0 14px", gap:8, flexShrink:0 },
  toolbarLogo: { fontSize:16, fontWeight:800, color:"#f0e8e0", letterSpacing:-0.5, marginRight:8 },
  toolbarDate: { fontSize:13, color:"#a09090", fontWeight:600, minWidth:60 },
  toolbarNextBtn: { background:"#800020", color:"#fff", border:"none", padding:"6px 14px", borderRadius:6, fontWeight:700, fontSize:13, cursor:"pointer" },
  toolbarFwdBtn: { background:"#3a2a2e", color:"#c8b8b0", border:"1px solid #5a3a3e", padding:"4px 10px", borderRadius:6, fontWeight:700, fontSize:12, cursor:"pointer" },
  toolbarMiniBtn: { background:"transparent", color:"#c0b0a8", border:"1px solid #5a3a3e", padding:"4px 9px", borderRadius:6, fontSize:12, cursor:"pointer" },
  toolbarWarn: { background:"#7a4800", color:"#ffd080", fontSize:12, fontWeight:700, padding:"3px 8px", borderRadius:10 },
  statusBar: { display:"flex", alignItems:"center", height:34, background:"#1e0e12", padding:"0 14px", gap:0, flexShrink:0, overflowX:"auto" as const },
  statusChip: { display:"flex", flexDirection:"column" as const, alignItems:"center", padding:"0 12px", borderRight:"1px solid #3a2a2e" },
  statusLabel: { fontSize:9, color:"#786868", textTransform:"uppercase" as const, letterSpacing:0.5 },
  statusValue: { fontSize:12, fontWeight:700, color:"#d0c8c0" },
  appLayout: { display:"flex", flexDirection:"column" as const, height:"100vh", overflow:"hidden", background:"#faf8f6" },
  contentRow: { display:"flex", flex:1, overflow:"hidden" },
  mapSection: { flex:1, overflow:"hidden", minWidth:260, position:"relative" as const },
  rightPanel: { width:420, display:"flex", flexDirection:"column" as const, borderLeft:"1px solid #e0d8d0", overflow:"hidden", flexShrink:0 },
  panelTabBar: { display:"flex", background:"#f5f0eb", borderBottom:"1px solid #e0d8d0", flexShrink:0 },
  panelTab: { background:"none", border:"none", padding:"9px 12px", fontSize:12, fontWeight:600, color:"#999", borderBottom:"2px solid transparent", marginBottom:-1, cursor:"pointer" },
  panelTabActive: { color:"#800020", borderBottom:"2px solid #800020" },
  panelContent: { flex:1, overflowY:"auto" as const },
  tableHead: { display:"flex", padding:"6px 12px", background:"#f0ebe5", borderBottom:"1px solid #e0d8d0", fontSize:11, fontWeight:700, color:"#888", textTransform:"uppercase" as const, letterSpacing:0.5, position:"sticky" as const, top:0 },
  tableRow: { display:"flex", alignItems:"center", padding:"7px 12px", borderBottom:"1px solid #f0ece8", fontSize:12, cursor:"pointer", gap:4 },
  tableRowAlt: { background:"#faf8f6" },
  tableRowActive: { background:"#f5e8e0" },
  tableExpanded: { background:"#fdf5f0", borderBottom:"1px solid #e8d8d0", padding:"10px 12px" },
  tableEmpty: { padding:"30px 16px", textAlign:"center" as const, color:"#aaa", fontSize:13 },
  miniActionBtn: { border:"none", color:"#fff", padding:"3px 10px", borderRadius:5, fontWeight:700, fontSize:11, cursor:"pointer" },
};
